twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        # get all route : used for footer 'map' and admin helper with errors 404 page
        ctAccessor: '@App\Services\CommonTwigAccessor'
